import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

// ── Enums ─────────────────────────────────────────────────────────────────────

export type InvoiceStatus =
  | 'draft'
  | 'issued'
  | 'sent'
  | 'paid'
  | 'partially_paid'
  | 'overdue'
  | 'cancelled'
  | 'voided';

export type InvoiceType =
  | 'booking'      // generated from a booking payment
  | 'membership'   // membership subscription invoice
  | 'academy'      // academy/coaching fees
  | 'manual'       // admin-created ad-hoc invoice
  | 'credit_note'; // reversal / refund credit note

/**
 * GST type determines which tax columns are applicable.
 *
 *   intra_state  → CGST + SGST applied (same state supplier and recipient)
 *   inter_state  → IGST applied (different state supplier and recipient)
 *   exempt       → No GST applies (exported services, exempt category)
 *   zero_rated   → 0% GST (SEZ supplies etc.)
 *   composite     → Composition scheme — single rate, no input credit
 */
export type GstType =
  | 'intra_state'
  | 'inter_state'
  | 'exempt'
  | 'zero_rated'
  | 'composite';

/**
 * InvoiceEntity — a full tax invoice with Indian GST support.
 *
 * Tax architecture:
 *   - All amounts stored in minor currency units (paise for INR).
 *   - subtotalMinor = sum of line items before tax.
 *   - CGST + SGST used for intra-state transactions.
 *   - IGST used for inter-state transactions.
 *   - CGST rate always equals SGST rate (each = half of total GST rate).
 *   - totalTaxMinor = CGST + SGST + IGST (only two of three ever non-zero).
 *   - grandTotalMinor = subtotalMinor + totalTaxMinor - discountMinor.
 *
 * Numbering:
 *   invoiceNumber generated by InvoiceNumberingService.
 *   Format: {PREFIX}/{FY}/{BRANCH_CODE}/{SEQUENCE}
 *   e.g. INV/2425/MUM/000042
 *
 * Table: invoices
 */
@Entity('invoices')
@Index(['tenantId', 'status'])
@Index(['tenantId', 'type'])
@Index(['tenantId', 'branchId'])
@Index(['tenantId', 'bookingId'])
@Index(['tenantId', 'userId'])
@Index(['tenantId', 'issuedAt'])
@Index(['tenantId', 'dueAt'])
@Index(['tenantId', 'invoiceNumber'], { unique: true })
@Index(['tenantId', 'isDeleted'])
export class InvoiceEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ name: 'tenant_id', type: 'uuid', nullable: false })
  @Index()
  tenantId!: string;

  // ── Reference ─────────────────────────────────────────────────────────────

  /**
   * Human-readable invoice number.
   * Unique per tenant. Generated by InvoiceNumberingService.
   * Format: INV/{FY}/{BRANCH_CODE}/{SEQ6}  e.g. INV/2425/MUM/000042
   */
  @Column({ name: 'invoice_number', type: 'varchar', length: 50, nullable: false })
  invoiceNumber!: string;

  @Column({
    type: 'enum',
    enum: ['draft', 'issued', 'sent', 'paid', 'partially_paid', 'overdue', 'cancelled', 'voided'],
    default: 'draft',
  })
  status!: InvoiceStatus;

  @Column({
    type: 'enum',
    enum: ['booking', 'membership', 'academy', 'manual', 'credit_note'],
    default: 'booking',
  })
  type!: InvoiceType;

  // ── Source resource links (all cross-service UUIDs, no DB FK) ─────────────

  @Column({ name: 'booking_id', type: 'uuid', nullable: true })
  bookingId!: string | null;

  @Column({ name: 'branch_id', type: 'uuid', nullable: false })
  branchId!: string;

  @Column({ name: 'user_id', type: 'uuid', nullable: true })
  userId!: string | null;

  /** For credit notes — the original invoice this reverses */
  @Column({ name: 'original_invoice_id', type: 'uuid', nullable: true })
  originalInvoiceId!: string | null;

  // ── Billing party ─────────────────────────────────────────────────────────

  @Column({ name: 'customer_name', type: 'varchar', length: 255, nullable: false })
  customerName!: string;

  @Column({ name: 'customer_email', type: 'varchar', length: 254, nullable: false })
  customerEmail!: string;

  @Column({ name: 'customer_phone', type: 'varchar', length: 30, nullable: true })
  customerPhone!: string | null;

  @Column({ name: 'customer_gstin', type: 'varchar', length: 15, nullable: true })
  customerGstin!: string | null;

  @Column({ name: 'billing_address', type: 'jsonb', nullable: true })
  billingAddress!: {
    line1:   string;
    line2?:  string;
    city:    string;
    state:   string;
    pincode: string;
    country?: string;
  } | null;

  // ── Supplier (tenant) GST details ─────────────────────────────────────────

  @Column({ name: 'supplier_gstin', type: 'varchar', length: 15, nullable: true })
  supplierGstin!: string | null;

  @Column({ name: 'supplier_state_code', type: 'varchar', length: 2, nullable: true })
  supplierStateCode!: string | null;

  @Column({ name: 'recipient_state_code', type: 'varchar', length: 2, nullable: true })
  recipientStateCode!: string | null;

  // ── GST classification ─────────────────────────────────────────────────────

  @Column({
    name: 'gst_type',
    type: 'enum',
    enum: ['intra_state', 'inter_state', 'exempt', 'zero_rated', 'composite'],
    default: 'intra_state',
  })
  gstType!: GstType;

  /** HSN/SAC code for the primary service on this invoice */
  @Column({ name: 'hsn_sac_code', type: 'varchar', length: 8, nullable: true })
  hsnSacCode!: string | null;

  // ── Line items ─────────────────────────────────────────────────────────────

  /**
   * Line items JSONB — array of InvoiceLineItem.
   * Each item carries its own taxable amount and GST rate.
   * Subtotals and tax totals are denormalised to the invoice row for fast queries.
   */
  @Column({ name: 'line_items', type: 'jsonb', nullable: false, default: '[]' })
  lineItems!: InvoiceLineItem[];

  // ── Amounts (all in minor currency units — paise for INR) ─────────────────

  /** Sum of (quantity × unitPriceMinor) across all line items — before discount/tax */
  @Column({ name: 'subtotal_minor', type: 'bigint', nullable: false })
  subtotalMinor!: number;

  /** Discount on the subtotal before tax */
  @Column({ name: 'discount_minor', type: 'bigint', default: 0 })
  discountMinor!: number;

  /** Taxable value = subtotalMinor - discountMinor */
  @Column({ name: 'taxable_value_minor', type: 'bigint', nullable: false })
  taxableValueMinor!: number;

  // ── CGST (intra-state, paid to central govt) ──────────────────────────────

  /** CGST rate in percentage × 100 (e.g. 900 = 9.00%) — always half of total GST rate */
  @Column({ name: 'cgst_rate_bps', type: 'int', default: 0 })
  cgstRateBps!: number;

  @Column({ name: 'cgst_amount_minor', type: 'bigint', default: 0 })
  cgstAmountMinor!: number;

  // ── SGST (intra-state, paid to state govt) ────────────────────────────────

  /** SGST rate in bps — always equals cgstRateBps */
  @Column({ name: 'sgst_rate_bps', type: 'int', default: 0 })
  sgstRateBps!: number;

  @Column({ name: 'sgst_amount_minor', type: 'bigint', default: 0 })
  sgstAmountMinor!: number;

  // ── IGST (inter-state, paid to central govt) ──────────────────────────────

  /** IGST rate in bps — equals cgstRateBps + sgstRateBps */
  @Column({ name: 'igst_rate_bps', type: 'int', default: 0 })
  igstRateBps!: number;

  @Column({ name: 'igst_amount_minor', type: 'bigint', default: 0 })
  igstAmountMinor!: number;

  // ── Cess (additional cess on luxury / demerit goods — sport equipment etc) -

  @Column({ name: 'cess_rate_bps', type: 'int', default: 0 })
  cessRateBps!: number;

  @Column({ name: 'cess_amount_minor', type: 'bigint', default: 0 })
  cessAmountMinor!: number;

  // ── Totals ─────────────────────────────────────────────────────────────────

  @Column({ name: 'total_tax_minor', type: 'bigint', nullable: false })
  totalTaxMinor!: number;

  @Column({ name: 'grand_total_minor', type: 'bigint', nullable: false })
  grandTotalMinor!: number;

  @Column({ name: 'amount_paid_minor', type: 'bigint', default: 0 })
  amountPaidMinor!: number;

  @Column({ name: 'balance_due_minor', type: 'bigint', nullable: false })
  balanceDueMinor!: number;

  @Column({ type: 'varchar', length: 3, default: 'INR' })
  currency!: string;

  // ── Dates ──────────────────────────────────────────────────────────────────

  @Column({ name: 'issued_at', type: 'timestamptz', nullable: true })
  issuedAt!: Date | null;

  @Column({ name: 'due_at', type: 'timestamptz', nullable: true })
  dueAt!: Date | null;

  @Column({ name: 'sent_at', type: 'timestamptz', nullable: true })
  sentAt!: Date | null;

  @Column({ name: 'paid_at', type: 'timestamptz', nullable: true })
  paidAt!: Date | null;

  // ── Notes ─────────────────────────────────────────────────────────────────

  @Column({ type: 'text', nullable: true })
  notes!: string | null;

  @Column({ name: 'internal_notes', type: 'text', nullable: true })
  internalNotes!: string | null;

  // ── Audit ─────────────────────────────────────────────────────────────────

  @Column({ name: 'created_by_id', type: 'uuid', nullable: true })
  createdById!: string | null;

  @Column({ name: 'updated_by_id', type: 'uuid', nullable: true })
  updatedById!: string | null;

  @Column({ name: 'is_deleted', type: 'boolean', default: false })
  isDeleted!: boolean;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt!: Date;

  @DeleteDateColumn({ name: 'deleted_at', type: 'timestamptz', nullable: true })
  deletedAt!: Date | null;
}

// ── Supporting types ──────────────────────────────────────────────────────────

export interface InvoiceLineItem {
  id:               string;    // UUID, stable across edits
  description:      string;
  hsnSacCode:       string | null;
  quantity:         number;    // decimal (e.g. 1.5 hours)
  unitPriceMinor:   number;    // price per unit in minor units
  subtotalMinor:    number;    // quantity × unitPriceMinor
  discountMinor:    number;    // discount on this line
  taxableMinor:     number;    // subtotalMinor - discountMinor
  gstRateBps:       number;    // total GST rate in bps (e.g. 1800 = 18%)
  cgstAmountMinor:  number;
  sgstAmountMinor:  number;
  igstAmountMinor:  number;
  totalMinor:       number;    // taxableMinor + all GST amounts
}
