import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

/**
 * Membership lifecycle states.
 * Stored as varchar (not DB enum) for forward-compatibility — new states
 * can be added without an ALTER TYPE migration.
 *
 * Allowed transitions enforced in MembershipService.
 *
 * Terminal states: upgraded | downgraded | expired | cancelled
 */
export type MembershipStatus =
  | 'trial'
  | 'pending_payment'
  | 'active'
  | 'frozen'
  | 'pending_renewal'
  | 'payment_failed'
  | 'cancellation_pending'
  | 'suspended'
  | 'upgraded'
  | 'downgraded'
  | 'expired'
  | 'cancelled';

/**
 * MembershipEntity — a member's enrolment in a plan.
 *
 * Owns the lifecycle state machine and a snapshot of plan benefits.
 * One user may have at most one non-terminal membership per tenant
 * (enforced at service layer; the unique index allows multiple terminal rows).
 *
 * Cross-service references (userId, createdById) are plain UUIDs —
 * no DB FK constraints.  Identity-service is the authoritative owner of users.
 *
 * Table: memberships
 */
@Entity('memberships')
@Index(['tenantId', 'userId'])
@Index(['tenantId', 'planId'])
@Index(['tenantId', 'status'])
@Index(['tenantId', 'memberNumber'], { unique: true, where: '"is_deleted" = false' })
@Index(['tenantId', 'renewsAt'], {
  where: `"status" IN ('active','pending_renewal','payment_failed')`,
})
@Index(['tenantId', 'expiresAt'], { where: '"expires_at" IS NOT NULL' })
@Index(['tenantId', 'isDeleted'])
export class MembershipEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ name: 'tenant_id', type: 'uuid', nullable: false })
  @Index()
  tenantId!: string;

  /** FK → membership_plans.id (same DB, no constraint — plan can be archived). */
  @Column({ name: 'plan_id', type: 'uuid', nullable: false })
  planId!: string;

  /**
   * FK → identity-service users.id (cross-service UUID reference, no DB FK).
   * nullable to support corporate seats where the seat is unoccupied.
   */
  @Column({ name: 'user_id', type: 'uuid', nullable: true })
  userId!: string | null;

  @Column({ name: 'membership_type', type: 'varchar', length: 50, nullable: false })
  membershipType!: string;

  /**
   * Human-readable reference (e.g. MBR-00042).
   * Generated by MembershipService.  Unique per tenant (partial index, non-deleted only).
   */
  @Column({ name: 'member_number', type: 'varchar', length: 30, nullable: false })
  memberNumber!: string;

  @Column({ name: 'status', type: 'varchar', length: 30, nullable: false, default: 'pending_payment' })
  status!: MembershipStatus;

  /**
   * Snapshot of the plan's benefit definitions at enrolment time.
   * Changing the plan after enrolment does NOT modify this snapshot.
   * This is the authoritative source of what THIS membership entitles the member to.
   */
  @Column({ name: 'benefit_snapshot', type: 'jsonb', nullable: false, default: '[]' })
  benefitSnapshot!: Record<string, unknown>[];

  /** ISO-4217 currency code — snapshotted from plan at enrolment. */
  @Column({ type: 'varchar', length: 3, nullable: false, default: 'GBP' })
  currency!: string;

  /** Recurring price in minor units — snapshotted from plan at enrolment. */
  @Column({ name: 'price_minor', type: 'int', nullable: false, default: 0 })
  priceMinor!: number;

  @Column({ name: 'auto_renew', type: 'boolean', nullable: false, default: true })
  autoRenew!: boolean;

  @Column({ name: 'enrolled_at', type: 'timestamptz', nullable: true })
  enrolledAt!: Date | null;

  @Column({ name: 'activated_at', type: 'timestamptz', nullable: true })
  activatedAt!: Date | null;

  @Column({ name: 'trial_ends_at', type: 'timestamptz', nullable: true })
  trialEndsAt!: Date | null;

  /** When the current membership period ends and renewal is due. null for lifetime plans. */
  @Column({ name: 'renews_at', type: 'timestamptz', nullable: true })
  renewsAt!: Date | null;

  /** Set when membership enters grace-period expiry path. */
  @Column({ name: 'expires_at', type: 'timestamptz', nullable: true })
  expiresAt!: Date | null;

  @Column({ name: 'cancelled_at', type: 'timestamptz', nullable: true })
  cancelledAt!: Date | null;

  @Column({ name: 'cancellation_reason', type: 'varchar', length: 500, nullable: true })
  cancellationReason!: string | null;

  /** Set when the membership is frozen. */
  @Column({ name: 'frozen_at', type: 'timestamptz', nullable: true })
  frozenAt!: Date | null;

  /** When the freeze automatically lifts. */
  @Column({ name: 'frozen_until', type: 'timestamptz', nullable: true })
  frozenUntil!: Date | null;

  /** Running total of days frozen this membership term. */
  @Column({ name: 'total_freeze_days_used', type: 'int', nullable: false, default: 0 })
  totalFreezeDaysUsed!: number;

  /**
   * Set when a downgrade is scheduled.
   * The current plan continues until renewsAt; the scheduler then creates a
   * new membership with this plan ID and terminates the current one.
   */
  @Column({ name: 'pending_downgrade_plan_id', type: 'uuid', nullable: true })
  pendingDowngradePlanId!: string | null;

  /**
   * FK → memberships.id — the parent membership for family/corporate sub-members.
   * null for primary / standalone memberships.
   */
  @Column({ name: 'parent_membership_id', type: 'uuid', nullable: true })
  parentMembershipId!: string | null;

  /**
   * For corporate seats: HR-assigned label for this seat (e.g. employee name before
   * the seat is linked to a userId).
   */
  @Column({ name: 'seat_label', type: 'varchar', length: 100, nullable: true })
  seatLabel!: string | null;

  @Column({ name: 'is_deleted', type: 'boolean', nullable: false, default: false })
  isDeleted!: boolean;

  @Column({ name: 'created_by_id', type: 'uuid', nullable: true })
  createdById!: string | null;

  @Column({ name: 'updated_by_id', type: 'uuid', nullable: true })
  updatedById!: string | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt!: Date;

  @DeleteDateColumn({ name: 'deleted_at', type: 'timestamptz', nullable: true })
  deletedAt!: Date | null;
}
