#!/usr/bin/env bash
# =============================================================================
# SPANCLE SPORTS OS — Per-Service Env File Generator
# scripts/gen-service-envs.sh
#
# Generates /etc/spancle/.env.<service> for each NestJS service from the
# master /etc/spancle/.env.production file.
#
# Each service env file contains only the vars that service needs, with
# DATABASE_URL pointing to its own database.
#
# Usage:
#   sudo ./scripts/gen-service-envs.sh
#
# Output files (owned by deploy:deploy, mode 600):
#   /etc/spancle/.env.identity
#   /etc/spancle/.env.saas-platform
#   /etc/spancle/.env.booking
#   /etc/spancle/.env.finance
#   /etc/spancle/.env.tournament
#   /etc/spancle/.env.academy
#   /etc/spancle/.env.communication
#   /etc/spancle/.env.reporting
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; NC='\033[0m'
log() { echo -e "${GREEN}[env-gen]${NC} $*"; }
err() { echo -e "${RED}[env-gen]${NC} $*" >&2; exit 1; }

MASTER_ENV="/etc/spancle/.env.production"
ENV_DIR="/etc/spancle"
DEPLOY_USER="${DEPLOY_USER:-deploy}"

[[ -f "$MASTER_ENV" ]] || err "Master env file not found: $MASTER_ENV"

# Load master env
set -a; source "$MASTER_ENV"; set +a

# ── Helper: write per-service env file ───────────────────────────────────────
write_env() {
  local name="$1"
  local db_url="$2"
  local extra="${3:-}"
  local out="$ENV_DIR/.env.$name"

  cat > "$out" << ENVEOF
# Auto-generated by gen-service-envs.sh — do not edit manually.
# Regenerate: sudo ./scripts/gen-service-envs.sh
NODE_ENV=${NODE_ENV:-production}
LOG_LEVEL=${LOG_LEVEL:-warn}

# Database — unique per service
DATABASE_URL=${db_url}
DATABASE_POOL_MIN=${DATABASE_POOL_MIN:-2}
DATABASE_POOL_MAX=${DATABASE_POOL_MAX:-10}
DATABASE_POOL_IDLE_TIMEOUT_MS=${DATABASE_POOL_IDLE_TIMEOUT_MS:-30000}
DATABASE_CONNECTION_TIMEOUT_MS=${DATABASE_CONNECTION_TIMEOUT_MS:-5000}
DATABASE_SSL=${DATABASE_SSL:-false}
DATABASE_SSL_REJECT_UNAUTHORIZED=${DATABASE_SSL_REJECT_UNAUTHORIZED:-true}

# Redis
REDIS_URL=${REDIS_URL}
REDIS_HOST=${REDIS_HOST:-127.0.0.1}
REDIS_PORT=${REDIS_PORT:-6379}
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_TLS=${REDIS_TLS:-false}
REDIS_DB_CACHE=${REDIS_DB_CACHE:-0}
REDIS_DB_SESSION=${REDIS_DB_SESSION:-1}
REDIS_DB_QUEUE=${REDIS_DB_QUEUE:-2}
REDIS_DB_PUBSUB=${REDIS_DB_PUBSUB:-3}

# JWT / Auth
JWT_SECRET=${JWT_SECRET}
JWT_ACCESS_TOKEN_EXPIRY=${JWT_ACCESS_TOKEN_EXPIRY:-15m}
JWT_REFRESH_TOKEN_EXPIRY=${JWT_REFRESH_TOKEN_EXPIRY:-7d}
JWT_ISSUER=${JWT_ISSUER:-spancle-sports-os}
JWT_SECRET_PREVIOUS=${JWT_SECRET_PREVIOUS:-}

# Multi-tenancy
TENANT_HEADER=${TENANT_HEADER:-x-tenant-id}

# CORS
CORS_ORIGINS=${CORS_ORIGINS}
CORS_CREDENTIALS=${CORS_CREDENTIALS:-true}

# Rate limiting
RATE_LIMIT_TTL_MS=${RATE_LIMIT_TTL_MS:-60000}
RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}

# Encryption
ENCRYPTION_KEY=${ENCRYPTION_KEY}
ENCRYPTION_KEY_VERSION=${ENCRYPTION_KEY_VERSION:-v1}

# Internal service URLs
IDENTITY_SERVICE_URL=${IDENTITY_SERVICE_URL:-http://127.0.0.1:3001}
SAAS_PLATFORM_SERVICE_URL=${SAAS_PLATFORM_SERVICE_URL:-http://127.0.0.1:3002}
BOOKING_SERVICE_URL=${BOOKING_SERVICE_URL:-http://127.0.0.1:3003}
FINANCE_SERVICE_URL=${FINANCE_SERVICE_URL:-http://127.0.0.1:3004}
TOURNAMENT_SERVICE_URL=${TOURNAMENT_SERVICE_URL:-http://127.0.0.1:3005}
ACADEMY_SERVICE_URL=${ACADEMY_SERVICE_URL:-http://127.0.0.1:3006}
COMMUNICATION_SERVICE_URL=${COMMUNICATION_SERVICE_URL:-http://127.0.0.1:3007}
REPORTING_SERVICE_URL=${REPORTING_SERVICE_URL:-http://127.0.0.1:3008}

# Email
SMTP_HOST=${SMTP_HOST:-}
SMTP_PORT=${SMTP_PORT:-587}
SMTP_SECURE=${SMTP_SECURE:-false}
SMTP_USER=${SMTP_USER:-}
SMTP_PASS=${SMTP_PASS:-}
SMTP_FROM=${SMTP_FROM:-noreply@spancle.io}

# Storage
STORAGE_DRIVER=${STORAGE_DRIVER:-local}
STORAGE_LOCAL_PATH=${STORAGE_LOCAL_PATH:-/var/spancle/uploads}

# Audit
AUDIT_LOG_ENABLED=${AUDIT_LOG_ENABLED:-true}
AUDIT_LOG_DRIVER=${AUDIT_LOG_DRIVER:-database}
AUDIT_LOG_RETENTION_DAYS=${AUDIT_LOG_RETENTION_DAYS:-365}

# Monitoring
SENTRY_DSN=${SENTRY_DSN:-}
SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-production}
${extra}
ENVEOF

  chmod 600 "$out"
  chown "${DEPLOY_USER}:${DEPLOY_USER}" "$out" 2>/dev/null || true
  log "  Written: $out"
}

# ── Generate per-service files ────────────────────────────────────────────────
log "Generating per-service env files..."

write_env "identity"      "${IDENTITY_DATABASE_URL}"
write_env "saas-platform" "${SAAS_DATABASE_URL}"
write_env "booking"       "${BOOKING_DATABASE_URL}"
write_env "finance"       "${FINANCE_DATABASE_URL}"
write_env "tournament"    "${TOURNAMENT_DATABASE_URL}"
write_env "academy"       "${ACADEMY_DATABASE_URL}"
write_env "communication" "${COMMUNICATION_DATABASE_URL}"
write_env "reporting"     "${REPORTING_DATABASE_URL}"

log "Done. Files in $ENV_DIR:"
ls -la "$ENV_DIR"/.env.* 2>/dev/null
